env:
  es6: true
extends: airbnb-base
overrides:
- files:
  - config/webpack/*.js
  env:
    commonjs: true
    node: true
- files:
  - app/assets/javascripts/**/*.js
  - app/javascript/**/*.js
  env:
    browser: true
  globals:
    App: false
    Rails: false
- files:
  - app/assets/javascripts/cable/cable.js
  globals:
    ActionCable: false
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  eqeqeq:
    - error
    - always
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  max-len:
  - error
  -
    code: 120
  no-unused-vars:
  - error
  -
    argsIgnorePattern: ^_
  quotes:
  - error
  - single
  semi:
  - error
  - never
  strict: 0
