env:
  es6: true
extends: airbnb-base
overrides:
- files:
  - app/assets/javascripts/*.js
  - app/javascript/packs/*.js
  env:
    browser: true
- files:
  - app/assets/javascripts/cable.js
  globals:
    ActionCable: false
- files:
  - config/webpack/*.js
  env:
    commonjs: true
    node: true
parserOptions:
  sourceType: module
rules:
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - always
