env:
  es6: true
extends: airbnb-base
overrides:
- files:
  - config/webpack/*.js
  env:
    commonjs: true
    node: true
- files:
  - app/assets/javascripts/**/*.js
  - app/javascript/packs/**/*.js
  env:
    browser: true
  globals:
    App: false
- files:
  - app/assets/javascripts/cable.js
  globals:
    ActionCable: false
parserOptions:
  sourceType: module
rules:
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  no-unused-vars:
  - error
  -
    argsIgnorePattern: ^_
  quotes:
  - error
  - single
  semi:
  - error
  - never
