AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - db/schema.rb
  - node_modules/**/*

# Exclude migrations in order to allow table-style arguments alignment
# https://github.com/bbatsov/rubocop/issues/5657
Layout/ExtraSpacing:
  Exclude:
  - 'db/migrate/**'

Metrics/LineLength:
  Max: 120
  Exclude:
  - 'db/migrate/**'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/**'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/**/*'

Style/StderrPuts:
  Enabled: false
