AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - db/schema.rb
  - node_modules/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/**/*'

Style/StderrPuts:
  Enabled: false
