# Linter Options
options:
  merge-default-rules: true
files:
  ignore:
  - node_modules/**/*
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  max-line-length:
  - 1
  -
    length: 120
  max-file-line-count: 1
  mixins-before-declarations:
  - 2
  -
    exclude:
    - breakpoint
    - mq

  no-css-comments: 0
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
  - 2
  -
    style: uppercase
  indentation:
  - 2
  -
    size: 2
  property-sort-order:
  - 1
  -
    ignore-custom-properties: false
    order:
    - display
    - margin
  variable-for-property:
  - 2
  -
    properties:
    - color
